### ISSUE TITLE
批量模式空行 bug

### ISSUE THREAD

**Issue by WeepingDogel** [WeepingDogel/TitleGetter#1]
当 `list.txt` 中出现空行时
```
https://github.com/WeepingDogel/TitleGetter
https://github.com/piggy-moe/subtitle
https://www.bilibili.com/


```

就会报错

```
weepingdogel@WeepingDogel ~/写/P/TitleGetter (master) [1]> proxychains -q python titlegetter.py

╭━━━━╮╭╮╭╮╱╱╱╱╭━━━╮╱╱╭╮╱╭╮
┃╭╮╭╮┣╯╰┫┃╱╱╱╱┃╭━╮┃╱╭╯╰┳╯╰╮
╰╯┃┃┣╋╮╭┫┃╭━━╮┃┃╱╰╋━┻╮╭┻╮╭╋━━┳━╮
╱╱┃┃┣┫┃┃┃┃┃┃━┫┃┃╭━┫┃━┫┃╱┃┃┃┃━┫╭╯
╱╱┃┃┃┃┃╰┫╰┫┃━┫┃╰┻━┃┃━┫╰╮┃╰┫┃━┫┃
╱╱╰╯╰╯╰━┻━┻━━╯╰━━━┻━━┻━╯╰━┻━━┻╯
    
Version: 1.0.1

Type a filename: try2
Requested Successfully
[GitHub - WeepingDogel/TitleGetter: 用来获取链接标题的小爬虫...](https://github.com/WeepingDogel/TitleGetter)
Requested Successfully
[GitHub - piggy-moe/subtitle: a command line tool for extracting hard-coded subtitles from videos](https://github.com/piggy-moe/subtitle)
Requested Successfully
[哔哩哔哩 (゜-゜)つロ 干杯~-bilibili](https://www.bilibili.com/)
Traceback (most recent call last):
  File "titlegetter.py", line 68, in <module>
    response = session.get(url,headers=headers)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

```

**Comment by WeepingDogel** [comment]
目前暂时只能先检测有没有空行然后直接结束程序提醒用户自己去掉了...
```python
# empty line checking
if url == '':
    print(empty_line_warning)
    urlist.close()
    os.remove("./out/" + filename + file_format)
    os._exit(0)
# empty line checking
```
太晚了，以后再想想怎么跳过吧...

**Comment by WeepingDogel** [comment]
已提交
